blank_issues_enabled: true
contact_links:
  - name: Monokle Community Support
    url: https://discord.com/channels/884464549347074049/885184274528075796
    about: Please ask and answer questions here.
