name: Production plugins push

on:
  push:
    tags:
    - 'validation/**'

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.15.1 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build app
        run: |
          NEWPATH=$(echo $RELEASE_VERSION | cut -d/ -f1-2)
          echo "NEWPATH=$NEWPATH" >> $GITHUB_ENV
          echo $NEWPATH
          cd $NEWPATH
          npm install 
          npm run build
          mv dist/{plugin,latest}.js
          find .
      - name: Login to GCP
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: 'Upload plugin'
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: '${{ env.NEWPATH }}/dist/latest.js'
          destination: 'monokle-cloud-plugins/${{ env.NEWPATH }}/'
      - name: 'Upload catalog.json'
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: 'validation/catalog.json'
          destination: 'monokle-cloud-plugins/validation/'
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
           SLACK_COLOR: ${{ job.status }} 
           SLACK_ICON: https://github.com/rtCamp.png?size=48
           SLACK_TITLE: Monokle cloud plugin release - ${{ steps.latest_commit.outputs.TITLE }}
           SLACK_WEBHOOK: ${{ secrets.RELEASE_NOTIF_SLACK_WEBHOOK }}
