name: Production plugins push
env:
  repo_name: kubeshop/monokle-saas-backend-production
  GKE_CLUSTER_NAME: final-prod-saas
  GKE_ZONE: us-east1-b

on:
  push:
    tags:
    - 'validation/**'

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.15.1 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build app
        run: |
          NEWPATH=$(echo $RELEASE_VERSION | cut -d/ -f1-2)
          echo "NEWPATH=$NEWPATH" >> $GITHUB_ENV
          echo $NEWPATH
          cd $NEWPATH
          npm install 
          npm run build
          find .
      - name: Login to GCP
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: 'upload-file'
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: './dist/plugin.js'
          destination: 'monokle-cloud-plugins/${{ env.NEWPATH }}/latest.js'
